version: "3"

services:
  # MySQL
  db:
    image: mysql:8.0.18
    container_name: mysql_con
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kadai
      MYSQL_USER:
      MYSQL_PASSWORD:
      TZ: "Asia/Tokyo"
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin_con
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_host
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
